name: dit
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  glob: ^2.1.2
  path: ^1.9.0


dev_dependencies:
  lints: ^3.0.0
